[build]
publish = "public"
command = "npm install && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "20"

[context.split1]
command = "npm install && hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
NODE_VERSION = "20"

[context.deploy-preview]
command = "npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.145.0"
NODE_VERSION = "20"

[context.branch-deploy]
command = "npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.145.0"
NODE_VERSION = "20"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

